<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ITOpsWorkspace.Core\ITOpsWorkspace.Core.csproj" />
    <ProjectReference Include="..\ITOpsWorkspace.Infrastructure\ITOpsWorkspace.Infrastructure.csproj" />
  </ItemGroup>

</Project>
